name: InstaWP WordPress Testing

on:
  pull_request:
    types: [opened]

jobs:
  create-wp-for-testing:
    runs-on: ubuntu-latest
    outputs:
      magic_login: ${{ steps.create-wp.outputs.magic_login }}
    steps:
      - uses: instawp/wordpress-testing-automation@main
        id: create-wp
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          INSTAWP_TOKEN: ${{secrets.INSTAWP_TOKEN}}
          INSTAWP_DOMAIN: ${{secrets.INSTAWP_DOMAIN}}
          INSTAWP_TEMPLATE_SLUG: qsmbugtesting
          REPO_ID: 7
  run-bugbug:
    needs: create-wp-for-testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g @testrevolution/bugbug-cli
      - run: bugbug config set-token ${{secrets.BUGBUG_TOKEN}}
      - run: bugbug remote run test b0c1b510-dde1-487d-b119-fe663c997809 --variable 'magiclogin=${{ needs.create-wp-for-testing.outputs.magic_login }}'
